version: "3"
services:
  api:
    image: bugatti:0.1-SNAPSHOT
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /config/google_stackdriver_creds.json
    ports:
      - "8080:8080"
    volumes:
      - ./api-logs:/logs
      - ./config:/config
    #logging:
      #driver: gcplogs
      #options:
        #gcp-project: gcmedia